import type { RiderResult } from "./types";

export const sampleRiders: RiderResult[] = [
  {
    id: "men-rowan-beck",
    name: "Rowan Beck",
    hometown: "Marquette, MI",
    category: "men",
    day1MovingTimeSeconds: 20260,
    day2SectorTimesSeconds: [714, 853, 603, 799],
    day2KomPoints: 28,
  },
  {
    id: "men-eli-madsen",
    name: "Eli Madsen",
    hometown: "Ishpeming, MI",
    category: "men",
    day1MovingTimeSeconds: 19930,
    day2SectorTimesSeconds: [720, 861, 598, 785],
    day2KomPoints: 24,
  },
  {
    id: "men-theo-carter",
    name: "Theo Carter",
    hometown: "Munising, MI",
    category: "men",
    day1MovingTimeSeconds: 20645,
    day2SectorTimesSeconds: [701, 845, 612, 772],
    day2KomPoints: 31,
  },
  {
    id: "men-mason-duval",
    name: "Mason Duval",
    hometown: "Negaunee, MI",
    category: "men",
    day1MovingTimeSeconds: 20955,
    day2SectorTimesSeconds: [736, 872, 621, 806],
    day2KomPoints: 19,
  },
  {
    id: "women-ada-keene",
    name: "Ada Keene",
    hometown: "Marquette, MI",
    category: "women",
    day1MovingTimeSeconds: 21704,
    day2SectorTimesSeconds: [765, 902, 645, 830],
    day2KomPoints: 26,
  },
  {
    id: "women-maris-holm",
    name: "Maris Holm",
    hometown: "Harvey, MI",
    category: "women",
    day1MovingTimeSeconds: 21502,
    day2SectorTimesSeconds: [758, 915, 639, 818],
    day2KomPoints: 22,
  },
  {
    id: "women-june-arquette",
    name: "June Arquette",
    hometown: "Munising, MI",
    category: "women",
    day1MovingTimeSeconds: 21911,
    day2SectorTimesSeconds: [749, 899, 633, 811],
    day2KomPoints: 29,
  },
  {
    id: "women-pilar-soto",
    name: "Pilar Soto",
    hometown: "Escanaba, MI",
    category: "women",
    day1MovingTimeSeconds: 22338,
    day2SectorTimesSeconds: [779, 921, 654, 842],
    day2KomPoints: 18,
  },
  {
    id: "nonbinary-avery-bloom",
    name: "Avery Bloom",
    hometown: "Marquette, MI",
    category: "non-binary",
    day1MovingTimeSeconds: 21319,
    day2SectorTimesSeconds: [744, 881, 628, 801],
    day2KomPoints: 23,
  },
  {
    id: "nonbinary-kit-mercer",
    name: "Kit Mercer",
    hometown: "Grand Marais, MI",
    category: "non-binary",
    day1MovingTimeSeconds: 21835,
    day2SectorTimesSeconds: [738, 875, 621, 796],
    day2KomPoints: 27,
  },
  {
    id: "nonbinary-river-saint",
    name: "River Saint",
    hometown: "Gwinn, MI",
    category: "non-binary",
    day1MovingTimeSeconds: 22023,
    day2SectorTimesSeconds: [752, 889, 635, 802],
    day2KomPoints: 20,
  },
  {
    id: "nonbinary-phoenix-hale",
    name: "Phoenix Hale",
    hometown: "Munising, MI",
    category: "non-binary",
    day1MovingTimeSeconds: 21548,
    day2SectorTimesSeconds: [747, 884, 626, 808],
    day2KomPoints: 25,
  },
];